### ISSUE TITLE
Corrupt mod downloaded by Wabbajack - skyrimse_v0473

### ISSUE THREAD

**Issue by Mikespnc** [SovnSkyrim/Aldrnari#36]
It Works find installing until I receive this message,
"D:\Wabbajack\Skyrim\downloads\Aldrnari - Open Perms Files.7z|Aldrnari - Open Perms Files\enbseries_skyrimse_v0473.zip is corrupt, please delete it and retry the installation".
Tried multiple times and no luck
Any help would be appreciated.

**Comment by SovnSkyrim** [comment]
please read the readme

**Comment by Mikespnc** [comment]
Instead of just putting please read the readme, why don't you actually help people and tell them where to read on the read me, instead of being a smart arse to people who need help.
Just not gonna use your modpack. Pathetic.

**Comment by Mikespnc** [comment]
Delete my comment then, truth hurts dosn't it.

**Comment by SovnSkyrim** [comment]
I dont give a fuck about losing an entitled user.

If you dont wanna read the readme to get accurate help or even your answer fixed by itself then I got no reason to write more.

I suppose this flew over your head.

You're the only one losing access to my work, it'll stay up for people who have been taught to read in preschool and I'll sleep just fine tonight.
